name: main

on:
  push:
      branches:
          - master
  pull_request:
      branches:
          - master

jobs:
    eslint:
        name: Run linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: npm install
            - name: Run eslint
              run: ./node_modules/.bin/eslint . --ext .js
    
    docker:
        name: Docker image
        runs-on: ubuntu-latest
        needs: eslint
        steps:
          - name: Checkout repo
            uses: actions/checkout@v3

          - name: Login to dockerhub
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set up docker buildx
            uses: docker/setup-buildx-action@v2

          - name: Build and push
            uses: docker/build-push-action@v4
            with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejsapp:latest
